export const FETCH_GENRE_INITIATED = "FETCH_GENRE_INITIATED";
export const FETCH_GENRE_FAILED = "FETCH_GENRE_FAILED";
export const FETCH_GENRE_SUCCEEDED = "FETCH_GENRE_SUCCEEDED";

export const FETCH_MOVIE_INITIATED = "FETCH_MOVIE_INITIATED";
export const FETCH_MOVIE_FAILED = "FETCH_MOVIE_FAILED";
export const FETCH_MOVIE_SUCCEEDED = "FETCH_MOVIE_SUCCEEDED";

export const FETCH_MOVIES_INITIATED = "FETCH_MOVIES_INITIATED";
export const FETCH_MOVIES_FAILED = "FETCH_MOVIES_FAILED";
export const FETCH_MOVIES_SUCCEEDED = "FETCH_MOVIES_SUCCEEDED";
export const FETCH_MOVIES_RESET = "FETCH_MOVIES_RESET";

export const GET_FAVORITE = "GET_FAVORITE";
export const REMOVED_FAVORITE = "REMOVED_FAVORITE";

export const SEARCH_QUERY_SUBMITTED = "SEARCH_QUERY_SUBMITTED";
